-- ============================================================================
-- PostgreSQL schema for crawler-POD — translated from the live SQLite schema.
--
-- Type mapping chosen so the application layer sees the SAME JavaScript types
-- it saw under better-sqlite3:
--
--   INTEGER PRIMARY KEY AUTOINCREMENT
--       -> INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--          ("BY DEFAULT", not "ALWAYS", so a future data import can supply the
--           original ids explicitly and then re-sync the sequences.)
--   REAL     -> DOUBLE PRECISION   float8 -> JS number.
--                                  NUMERIC would arrive as a *string*.
--   INTEGER  -> INTEGER            int4 -> JS number.
--                                  BIGINT/int8 would arrive as a *string*.
--   TEXT     -> TEXT
--   DATETIME -> TEXT               see the timestamp note below.
--
-- TIMESTAMP NOTE — deliberate, not an oversight:
-- SQLite has no native date type; every timestamp here is already stored as
-- TEXT, and the live data holds TWO formats side by side:
--     '2026-08-22 03:12:36'        (SQLite CURRENT_TIMESTAMP style)
--     '2026-09-05T06:41:50.436Z'   (JavaScript toISOString style)
-- The application compares these as strings and normalises them itself
-- (formatVietnamTime / normalizeLegacyUtcTimestamp). Mapping them to TIMESTAMPTZ
-- would fail to parse the mixed formats uniformly AND make node-postgres return
-- Date objects, silently breaking every string comparison in the codebase.
-- The DEFAULT below reproduces SQLite's CURRENT_TIMESTAMP format exactly; the
-- pg-client adapter rewrites in-query CURRENT_TIMESTAMP the same way.
-- ============================================================================

CREATE TABLE IF NOT EXISTS platforms (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT UNIQUE NOT NULL,
  display_name    TEXT NOT NULL,
  description     TEXT,
  query_type      TEXT DEFAULT 'keyword',
  actor_id        TEXT NOT NULL,
  country_support INTEGER DEFAULT 0,
  icon            TEXT DEFAULT '🔗',
  color           TEXT DEFAULT '#888888'
);

CREATE TABLE IF NOT EXISTS runs (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform         TEXT NOT NULL,
  query            TEXT NOT NULL,
  status           TEXT DEFAULT 'pending',
  apify_run_id     TEXT,
  apify_dataset_id TEXT,
  items_count      INTEGER DEFAULT 0,
  new_count        INTEGER DEFAULT 0,
  active_count     INTEGER DEFAULT 0,
  dropped_count    INTEGER DEFAULT 0,
  error_message    TEXT,
  max_items        INTEGER DEFAULT 100,
  country          TEXT,
  input_options    TEXT DEFAULT '{}',
  created_at       TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  completed_at     TEXT,
  active_backend          TEXT,
  backend_kind            TEXT,
  backend_status          TEXT,
  backend_version         TEXT,
  backend_run_id          TEXT,
  health_snapshot         TEXT,
  cost_estimate           DOUBLE PRECISION DEFAULT 0,
  parent_run_id           INTEGER,
  result_items_json       TEXT,
  external_execution_json TEXT
);

CREATE TABLE IF NOT EXISTS snapshots (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id           INTEGER NOT NULL,
  platform         TEXT NOT NULL,
  query            TEXT NOT NULL,
  item_uid         TEXT NOT NULL,
  raw_data         TEXT NOT NULL,
  title            TEXT DEFAULT '',
  url              TEXT DEFAULT '',
  image            TEXT DEFAULT '',
  author           TEXT DEFAULT '',
  price            DOUBLE PRECISION DEFAULT 0,
  rating           DOUBLE PRECISION DEFAULT 0,
  reviews          INTEGER DEFAULT 0,
  sold_count       INTEGER DEFAULT 0,
  likes            INTEGER DEFAULT 0,
  comments         INTEGER DEFAULT 0,
  shares           INTEGER DEFAULT 0,
  views            INTEGER DEFAULT 0,
  status           TEXT DEFAULT 'new',
  prev_snapshot_id INTEGER,
  created_at       TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product_current (
  item_uid          TEXT PRIMARY KEY,
  platform          TEXT NOT NULL,
  query             TEXT NOT NULL DEFAULT '',
  title             TEXT NOT NULL DEFAULT '',
  url               TEXT NOT NULL DEFAULT '',
  image             TEXT NOT NULL DEFAULT '',
  author            TEXT NOT NULL DEFAULT '',

  current_price     DOUBLE PRECISION NOT NULL DEFAULT 0,
  current_rating    DOUBLE PRECISION NOT NULL DEFAULT 0,
  current_reviews   INTEGER NOT NULL DEFAULT 0,
  current_sold      INTEGER NOT NULL DEFAULT 0,
  current_likes     INTEGER NOT NULL DEFAULT 0,
  current_comments  INTEGER NOT NULL DEFAULT 0,
  current_shares    INTEGER NOT NULL DEFAULT 0,
  current_views     INTEGER NOT NULL DEFAULT 0,

  prev_price        DOUBLE PRECISION,
  prev_likes        INTEGER,
  prev_comments     INTEGER,
  prev_shares       INTEGER,
  prev_views        INTEGER,
  prev_sold         INTEGER,
  prev_reviews      INTEGER,

  delta_price       DOUBLE PRECISION NOT NULL DEFAULT 0,
  delta_likes       INTEGER NOT NULL DEFAULT 0,
  delta_comments    INTEGER NOT NULL DEFAULT 0,
  delta_shares      INTEGER NOT NULL DEFAULT 0,
  delta_views       INTEGER NOT NULL DEFAULT 0,
  delta_sold        INTEGER NOT NULL DEFAULT 0,
  delta_reviews     INTEGER NOT NULL DEFAULT 0,

  delta_3h_likes    INTEGER,
  delta_3h_views    INTEGER,
  delta_24h_likes   INTEGER,
  delta_24h_views   INTEGER,
  delta_24h_sold    INTEGER,

  rank_score        DOUBLE PRECISION NOT NULL DEFAULT 0,
  status            TEXT NOT NULL DEFAULT 'new',
  last_run_id       INTEGER,
  observation_count INTEGER NOT NULL DEFAULT 1,

  first_seen_at     TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_seen_at      TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_crawled_at   TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  prev_rating       DOUBLE PRECISION,
  delta_rating      DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS daily_packed_history (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_uid          TEXT NOT NULL,
  platform          TEXT NOT NULL,
  date              TEXT NOT NULL,
  observations_json TEXT NOT NULL DEFAULT '[]',
  observation_count INTEGER NOT NULL DEFAULT 0,
  min_price         DOUBLE PRECISION NOT NULL DEFAULT 0,
  max_price         DOUBLE PRECISION NOT NULL DEFAULT 0,
  latest_price      DOUBLE PRECISION NOT NULL DEFAULT 0,
  latest_likes      INTEGER NOT NULL DEFAULT 0,
  latest_views      INTEGER NOT NULL DEFAULT 0,
  latest_sold       INTEGER NOT NULL DEFAULT 0,
  created_at        TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at        TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (item_uid, date)
);

CREATE TABLE IF NOT EXISTS weekly_summary (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_uid          TEXT NOT NULL,
  platform          TEXT NOT NULL,
  year_week         TEXT NOT NULL,
  avg_price         DOUBLE PRECISION NOT NULL DEFAULT 0,
  max_likes         INTEGER NOT NULL DEFAULT 0,
  max_views         INTEGER NOT NULL DEFAULT 0,
  delta_likes       INTEGER NOT NULL DEFAULT 0,
  delta_views       INTEGER NOT NULL DEFAULT 0,
  delta_sold        INTEGER NOT NULL DEFAULT 0,
  growth_rate       DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at        TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at        TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  sample_count      INTEGER NOT NULL DEFAULT 0,
  sum_price         DOUBLE PRECISION NOT NULL DEFAULT 0,
  first_price       DOUBLE PRECISION,
  last_price        DOUBLE PRECISION,
  first_views       INTEGER,
  last_views        INTEGER,
  first_likes       INTEGER,
  last_likes        INTEGER,
  first_sold        INTEGER,
  last_sold         INTEGER,
  first_comments    INTEGER,
  last_comments     INTEGER,
  first_shares      INTEGER,
  last_shares       INTEGER,
  UNIQUE (item_uid, year_week)
);

CREATE TABLE IF NOT EXISTS marketplace_proxies (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label            TEXT NOT NULL UNIQUE,
  protocol         TEXT NOT NULL DEFAULT 'socks5',
  host             TEXT NOT NULL,
  port             INTEGER NOT NULL,
  config_encrypted TEXT NOT NULL,
  created_at       TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at       TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS marketplace_accounts (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform          TEXT NOT NULL,
  label             TEXT NOT NULL,
  session_encrypted TEXT NOT NULL,
  proxy_id          INTEGER,
  created_at        TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at        TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (platform, label),
  FOREIGN KEY (proxy_id) REFERENCES marketplace_proxies(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS marketplace_captures (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform       TEXT NOT NULL,
  account_id     INTEGER,
  url            TEXT NOT NULL,
  html_encrypted TEXT NOT NULL,
  html_sha256    TEXT NOT NULL,
  parsed_data    TEXT NOT NULL,
  variant_mode   TEXT NOT NULL DEFAULT 'base',
  max_variants   INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY (account_id) REFERENCES marketplace_accounts(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS marketplace_capture_schedules (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform      TEXT NOT NULL,
  keyword       TEXT NOT NULL,
  account_id    INTEGER,
  every_minutes INTEGER NOT NULL,
  schedule_type TEXT NOT NULL DEFAULT 'interval',
  daily_time    TEXT,
  run_at        TEXT,
  variant_mode  TEXT NOT NULL DEFAULT 'base',
  max_variants  INTEGER NOT NULL DEFAULT 0,
  max_listings  INTEGER NOT NULL DEFAULT 30,
  enabled       INTEGER NOT NULL DEFAULT 1,
  next_run_at   TEXT NOT NULL,
  last_run_at   TEXT,
  last_summary  TEXT,
  created_at    TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  claimed_until TEXT,
  claim_token   TEXT,
  FOREIGN KEY (account_id) REFERENCES marketplace_accounts(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS marketplace_capture_schedule_runs (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id  INTEGER NOT NULL,
  summary      TEXT NOT NULL,
  completed_at TEXT NOT NULL,
  FOREIGN KEY (schedule_id) REFERENCES marketplace_capture_schedules(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS social_bot_state (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_key          TEXT NOT NULL,
  scheduled_window INTEGER NOT NULL,
  query_key        TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending',
  run_id           INTEGER,
  error_message    TEXT,
  created_at       TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at       TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (bot_key, scheduled_window, query_key)
);

CREATE TABLE IF NOT EXISTS v2_write_failures (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id        INTEGER,
  item_uid      TEXT NOT NULL,
  error_message TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending',
  created_at    TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS migration_checkpoints (
  key        TEXT PRIMARY KEY,
  value      TEXT,
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

-- ==================== Indexes (1:1 with the SQLite set) ====================
CREATE INDEX IF NOT EXISTS idx_daily_history_platform_date ON daily_packed_history (platform, date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_history_uid_date ON daily_packed_history (item_uid, date DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_capture_schedule_runs_schedule ON marketplace_capture_schedule_runs (schedule_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_capture_schedules_due ON marketplace_capture_schedules (enabled, next_run_at);
CREATE INDEX IF NOT EXISTS idx_marketplace_captures_cache ON marketplace_captures (platform, url, account_id, variant_mode, max_variants, id DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_captures_platform ON marketplace_captures (platform, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_current_last_crawled ON product_current (last_crawled_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_current_platform_crawled ON product_current (platform, last_crawled_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_current_platform_rank ON product_current (platform, rank_score DESC);
CREATE INDEX IF NOT EXISTS idx_product_current_query ON product_current (platform, query);
CREATE INDEX IF NOT EXISTS idx_runs_parent ON runs (parent_run_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_latest ON snapshots (platform, query, run_id DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_platform_query ON snapshots (platform, query);
CREATE INDEX IF NOT EXISTS idx_snapshots_run ON snapshots (run_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_uid ON snapshots (item_uid);
CREATE INDEX IF NOT EXISTS idx_social_bot_state_bot ON social_bot_state (bot_key, scheduled_window DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_summary_platform_week ON weekly_summary (platform, year_week DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_summary_uid_week ON weekly_summary (item_uid, year_week DESC);

-- ==================== Additive migrations ====================
-- This file is replayed on every boot (initDatabase -> db.exec) and every
-- CREATE TABLE above is IF NOT EXISTS, so a table that already exists is left
-- exactly as it is. New columns therefore have to be added explicitly here;
-- ADD COLUMN IF NOT EXISTS keeps that replay idempotent.

-- Task 1 (Instagram media): a post's media is not just one image. Video posts
-- carry a separate direct CDN URL and carousels carry several media of mixed
-- type, so "which media does this row have" cannot be derived from `image`.
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS video_url  TEXT NOT NULL DEFAULT '';
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS media_type TEXT NOT NULL DEFAULT '';

-- Task 5 (TikTok Shop daily Top 20). return_position is the position the
-- provider returned the product in — NOT a rank: the actor publishes no rank
-- field and its results are not sorted by sales, so calling it rank would
-- assert ordering semantics the provider never confirmed. prev_/delta_ mirror
-- the pattern the other metrics already use, so "moved up 3 places since
-- yesterday" is answerable from one row.
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS return_position       INTEGER;
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS prev_return_position  INTEGER;
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS delta_return_position INTEGER;
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS sold_30d              INTEGER;
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS gmv                   DOUBLE PRECISION;
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS shop_url              TEXT NOT NULL DEFAULT '';
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS country               TEXT NOT NULL DEFAULT '';

-- Task 5.2: a schedule has to be able to say WHICH market it targets. TikTok
-- Shop's actor requires country_code, and "press on nails / US" is a different
-- job from "press on nails / UK" — without this column every scheduled run fell
-- back to the actor default and the market was unspecifiable.
ALTER TABLE marketplace_capture_schedules ADD COLUMN IF NOT EXISTS country TEXT NOT NULL DEFAULT '';

-- "Saves" / "Lưu": TikTok's collectCount. A distinct signal from shares — a save
-- is intent to come back, a share is distribution — so it gets its own column
-- rather than being folded into current_shares, where it would silently inflate
-- a different metric.
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS current_saves INTEGER NOT NULL DEFAULT 0;
ALTER TABLE product_current ADD COLUMN IF NOT EXISTS prev_saves    INTEGER;

/*
 * Full comment text, one row per comment.
 *
 * Kept out of product_current deliberately: a post has many comments, they are
 * text rather than a metric, and product_current holds one row per item. A child
 * table keeps every comment queryable — search the text, rank by likes, walk a
 * reply thread — instead of burying them in a JSON blob.
 *
 * comment_id is the provider's own id (TikTok's `cid`), so re-crawling a post
 * updates its comments in place instead of duplicating them.
 * parent_comment_id is set for replies (TikTok's `repliesToId`).
 */
CREATE TABLE IF NOT EXISTS post_comments (
  item_uid          TEXT NOT NULL,
  comment_id        TEXT NOT NULL,
  platform          TEXT NOT NULL DEFAULT '',
  parent_comment_id TEXT,
  author            TEXT NOT NULL DEFAULT '',
  text              TEXT NOT NULL DEFAULT '',
  likes             INTEGER NOT NULL DEFAULT 0,
  reply_count       INTEGER NOT NULL DEFAULT 0,
  liked_by_author   BOOLEAN NOT NULL DEFAULT FALSE,
  pinned_by_author  BOOLEAN NOT NULL DEFAULT FALSE,
  commented_at      TEXT NOT NULL DEFAULT '',
  run_id            INTEGER,
  collected_at      TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (item_uid, comment_id)
);

CREATE INDEX IF NOT EXISTS idx_post_comments_item   ON post_comments (item_uid, likes DESC);
CREATE INDEX IF NOT EXISTS idx_post_comments_parent ON post_comments (item_uid, parent_comment_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_run    ON post_comments (run_id);
