/**
 * E2E Test Harness & Specification Oracles for Two-Tier Data Tracking System.
 *
 * Implements SSOT rules from docs/DISCOVERY_MONITORING_PLAN_REVISED.md:
 * - §3.1 & §4: Identity, composite keys, pending identity, schema definitions
 * - §3.2: Shop lifecycle, 30-day unchanged baseline, 7-day max observation gap, UI label
 * - §3.3: Social author lifecycle, 30/60-day deadlines, star/unstar dynamics, tick expiry
 * - §5: Shared patch writer (field-presence merge), advisory locks, observation deduplication
 * - §6 & §10: Global limiter (max 1 concurrent capture, 20s cooldown lease, fencing tokens)
 * - Stealth Browser (CloakBrowser priority + Camoufox fallback) & Admin Dashboard API
 */
const fs = require('fs');
const path = require('path');
const { fromDriver } = require('../../src/database/pg-client');
const { applyMonitoringObservation } = require('../../src/database/monitoring');

const BASE_SCHEMA = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'database', 'pg-schema.sql'), 'utf8');

const MONITORING_DDL = `
-- ==================== Monitoring DDL (SSOT §4) ====================
CREATE TABLE IF NOT EXISTS monitoring_entities (
  id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform                   TEXT NOT NULL,
  entity_type                TEXT NOT NULL CHECK (entity_type IN ('shop', 'author')),
  external_id                TEXT NOT NULL,
  canonical_url              TEXT,
  display_name               TEXT,
  identity_source            TEXT NOT NULL,
  identity_confidence        DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  tracking_status            TEXT NOT NULL DEFAULT 'active' CHECK (tracking_status IN ('active', 'paused', 'stopped', 'expired')),
  reason                     TEXT,
  is_starred                 BOOLEAN NOT NULL DEFAULT FALSE,
  session_id                 TEXT NOT NULL,
  monitoring_started_at      TIMESTAMPTZ NOT NULL,
  expires_at                 TIMESTAMPTZ,
  entity_next_due_at         TIMESTAMPTZ NOT NULL,
  last_success_at            TIMESTAMPTZ,
  sales                      BIGINT,
  sales_observed_at          TIMESTAMPTZ,
  unchanged_since            TIMESTAMPTZ,
  last_increase_observed_at  TIMESTAMPTZ,
  policy_version             INTEGER NOT NULL DEFAULT 1,
  state_version              INTEGER NOT NULL DEFAULT 1,
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (platform, entity_type, external_id)
);

CREATE INDEX IF NOT EXISTS idx_monitoring_entities_due 
  ON monitoring_entities (entity_next_due_at) 
  WHERE tracking_status = 'active';

CREATE INDEX IF NOT EXISTS idx_monitoring_entities_expiry 
  ON monitoring_entities (expires_at) 
  WHERE tracking_status = 'active';

CREATE TABLE IF NOT EXISTS monitoring_items (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_uid              TEXT NOT NULL UNIQUE REFERENCES product_current(item_uid) ON DELETE CASCADE,
  entity_id             INTEGER REFERENCES monitoring_entities(id) ON DELETE SET NULL,
  eligibility           TEXT NOT NULL DEFAULT 'ready' CHECK (eligibility IN ('ready', 'pending_identity', 'unsupported')),
  item_status           TEXT NOT NULL DEFAULT 'active' CHECK (item_status IN ('active', 'paused', 'unavailable')),
  next_due_at           TIMESTAMPTZ,
  last_attempt_at       TIMESTAMPTZ,
  last_success_at       TIMESTAMPTZ,
  consecutive_failures  INTEGER NOT NULL DEFAULT 0,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_monitoring_items_entity_due 
  ON monitoring_items (entity_id, next_due_at) 
  WHERE item_status = 'active';

CREATE TABLE IF NOT EXISTS monitoring_jobs (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id        INTEGER REFERENCES monitoring_entities(id) ON DELETE CASCADE,
  item_id          INTEGER REFERENCES monitoring_items(id) ON DELETE CASCADE,
  kind             TEXT NOT NULL CHECK (kind IN ('shop_probe', 'item_refresh')),
  session_id       TEXT NOT NULL,
  scheduled_for    TIMESTAMPTZ NOT NULL,
  status           TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'claimed', 'running', 'completed', 'failed', 'cancelled')),
  attempt_count    INTEGER NOT NULL DEFAULT 0,
  retry_at         TIMESTAMPTZ,
  claimed_until    TIMESTAMPTZ,
  claim_token      TEXT,
  execution_token  TEXT,
  observation_id   TEXT,
  state_version    INTEGER NOT NULL DEFAULT 1,
  started_at       TIMESTAMPTZ,
  finished_at      TIMESTAMPTZ,
  error_message    TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    (kind = 'shop_probe' AND entity_id IS NOT NULL AND item_id IS NULL) OR
    (kind = 'item_refresh' AND item_id IS NOT NULL)
  ),
  UNIQUE (kind, entity_id, item_id, session_id, scheduled_for)
);

CREATE INDEX IF NOT EXISTS idx_monitoring_jobs_ready 
  ON monitoring_jobs (status, scheduled_for, retry_at) 
  WHERE status IN ('queued', 'failed');

CREATE TABLE IF NOT EXISTS monitoring_entity_observations (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id       INTEGER NOT NULL REFERENCES monitoring_entities(id) ON DELETE CASCADE,
  session_id      TEXT NOT NULL,
  observation_id  TEXT NOT NULL UNIQUE,
  observed_at     TIMESTAMPTZ NOT NULL,
  metric_name     TEXT NOT NULL,
  metric_value    DOUBLE PRECISION,
  source          TEXT NOT NULL,
  quality         TEXT NOT NULL CHECK (quality IN ('exact', 'rounded', 'estimated', 'unreliable', 'recalibrated')),
  raw_ref         TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_monitoring_obs_entity_date 
  ON monitoring_entity_observations (entity_id, observed_at DESC);

CREATE TABLE IF NOT EXISTS monitoring_limiter (
  key             TEXT PRIMARY KEY,
  owner_token     TEXT,
  leased_until    TIMESTAMPTZ,
  next_allowed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
`;

/**
 * Creates an isolated in-memory PGlite test database with both base schema
 * and the 5 monitoring tables initialized.
 */
async function createTestDb() {
  const { PGlite } = await import('@electric-sql/pglite');
  const driver = new PGlite();
  const db = fromDriver(driver);
  await db.exec(BASE_SCHEMA);
  await db.exec(MONITORING_DDL);
  return db;
}

/**
 * Deterministic Virtual Clock for simulating time progression
 * across 30-day, 60-day, and 5-day cycle boundaries.
 */
class VirtualClock {
  constructor(initialEpoch = '2026-09-01T00:00:00.000Z') {
    this.currentMs = new Date(initialEpoch).getTime();
  }

  now() {
    return new Date(this.currentMs);
  }

  nowISO() {
    return new Date(this.currentMs).toISOString();
  }

  advanceSeconds(sec) {
    this.currentMs += sec * 1000;
    return this.now();
  }

  advanceMinutes(min) {
    this.currentMs += min * 60 * 1000;
    return this.now();
  }

  advanceHours(hours) {
    this.currentMs += hours * 3600 * 1000;
    return this.now();
  }

  advanceDays(days) {
    this.currentMs += days * 86400 * 1000;
    return this.now();
  }

  setTime(epochStr) {
    this.currentMs = new Date(epochStr).getTime();
    return this.now();
  }
}

const {
  ShopLifecyclePolicy,
  CONSTANTS: PROD_SHOP_CONSTANTS,
  computeNextDue,
  computeNextDueAt,
  computeBackoffRetryAt,
  isGapBroken,
  calculateElapsedWindow,
  evaluateAndApplyShopProbe,
} = require('../../src/monitoring/shop-lifecycle');

const {
  SocialLifecyclePolicy,
  CONSTANTS: PROD_SOCIAL_CONSTANTS,
  calculateExpiresAt,
  computeInitialExpiresAt,
  handleStar,
  handleUnstar,
  setStarred,
  checkExpiration,
  evaluateTickExpiry,
  handleRetrack,
  retrack,
  canDispatchJob,
  canCommitResult,
  evaluateAndApplyAuthorStar,
  evaluateAndApplyAuthorUnstar,
  evaluateAndApplyTickExpiry,
  evaluateAndApplyAuthorRetrack,
} = require('../../src/monitoring/social-lifecycle');

/**
 * Constants defined in SSOT §3.2, §3.3, §6
 */
const CONSTANTS = {
  ...PROD_SHOP_CONSTANTS,
  ...PROD_SOCIAL_CONSTANTS,
  MONITOR_ITEM_DELAY_MS: 20000,                           // 20 seconds cooldown
  DEFAULT_CYCLE_INTERVAL_DAYS: 5,
};

const { hashItemUidToAdvisoryKey } = require('../../src/database/concurrency');
const { buildObservationId } = require('../../src/database/daily-history');
const { MonitoringLimiter } = require('../../src/monitoring/limiter');

const { StealthBrowserRunner } = require('../../src/marketplaces/stealth-browser');
const { AdminDashboardService } = require('../../src/admin/dashboard');

module.exports = {
  BASE_SCHEMA,
  MONITORING_DDL,
  CONSTANTS,
  createTestDb,
  VirtualClock,
  ShopLifecyclePolicy,
  SocialLifecyclePolicy,
  computeNextDue,
  computeNextDueAt,
  computeBackoffRetryAt,
  isGapBroken,
  calculateElapsedWindow,
  evaluateAndApplyShopProbe,
  calculateExpiresAt,
  computeInitialExpiresAt,
  handleStar,
  handleUnstar,
  setStarred,
  checkExpiration,
  evaluateTickExpiry,
  handleRetrack,
  retrack,
  canDispatchJob,
  canCommitResult,
  evaluateAndApplyAuthorStar,
  evaluateAndApplyAuthorUnstar,
  evaluateAndApplyTickExpiry,
  evaluateAndApplyAuthorRetrack,
  hashItemUidToAdvisoryKey,
  buildObservationId,
  applyMonitoringObservation,
  MonitoringLimiter,
  StealthBrowserRunner,
  AdminDashboardService,
};
